/*
 HTML5 Video Player
 Version: 1.0.6
 (c) 2012 DMXzone.com
 @build 31-10-2012 16:13:17
*/
(function(j){var m={plugins:["Display","Startbutton","Controlbar","Bufferingicon"],width:570,height:320,controls:!0,_debug:!1};j.fn.dmxHTML5VideoPlayer=function(c){function g(b,a){var c=a.getItemConfig("title",a.getItemIdx());c||(c="");return b.replace(/##index##/g,a.getItemIdx()).replace(/##nr##/g,a.getItemIdx()+1).replace(/##title##/g,c.replace(/'/g,"\\'").replace(/"/g,'\\"'.replace(/([\n\r\t])/g,"\\$1"))).replace(/##time##/g,k(a.getPosition())).replace(/##remaining##/g,k(a.getDuration()-a.getPosition())).replace(/##duration##/g,
k(a.getDuration())).replace(/##position##/g,n(a.getPosition(),a.getDuration())).replace(/##volume##/g,a.getVolume())}function n(b,a){return Math.round(100*b/a)||0}function k(b){var a=new Date(b);a.getUTCHours();b=a.getUTCMinutes();a=a.getUTCSeconds();return""+((10>b?"0"+b:b)+":")+((10>a?"0"+a:a)+"")}function l(b){b=String(b);b=jQuery('<a href="'+b+'" />');return String(String(b[0].href))}var i=/chrome/.test(navigator.userAgent.toLowerCase()),d;a:{d=jQuery('script[src*="ScriptLibrary/dmxHTML5VideoPlayer.js"]');
if(0<d.length){d=d.eq(0).attr("src");var b=d.indexOf("dmxHTML5VideoPlayer.js");if(-1!=b){d=d.substring(0,b);break a}}d=""}b=d+"jarisplayer.swf";c=j.extend(m,c,{useYTIframeAPI:!0,playerFlashMP4:b,playerFlashMP3:b,defaultPoster:d+"html5_video_player_poster_nobutton.jpg",imageScaling:"fill"});l(d);for(var h=0;h<c.playlist.length;h++){for(var b=c.playlist[h],e=0;3>e;e++)b[e]&&b[e].src&&(b[e].src=l(b[e].src));if(b[0]&&b[0].src&&-1!=b[0].src.search(/\/vid\.ly\//)&&(e=b[0].src.replace(/\/$/,"").match(/\/vid\.ly\/(\w+)/))&&
0<e.length)e=e[1],b[0]={src:"http://vidly.s3.amazonaws.com/"+e+"/mp4.mp4",type:"video/mp4"},b[1]={src:"http://vidly.s3.amazonaws.com/"+e+"/webm.webm",type:"video/webm"},b[2]={src:"http://vidly.s3.amazonaws.com/"+e+"/ogv.ogv",type:"video/ogg"};i&&(b[0]&&b[1])&&(e=b[1],b[1]=b[0],b[0]=e)}c.volume&&0<c.volume&&(c.volume/=100);c.poster||(c.poster=d+"html5_video_player_poster_nobutton.jpg");c.currentItemPlaying=-1;i=!1;d=navigator;var b=d.plugins,f,h=window.ActiveXObject;if(b&&b.length)(f=d.mimeTypes)&&
(f["application/x-shockwave-flash"]&&f["application/x-shockwave-flash"].enabledPlugin&&f["application/x-shockwave-flash"].enabledPlugin.description)&&(i=!0);else if("undefined"!==typeof h){try{f=new h("ShockwaveFlash.ShockwaveFlash")}catch(o){}i=!!f}if(!i)for(f=0;f<projekktor.mmap.length;f++)"ytvideo"==projekktor.mmap[f].model&&(projekktor.mmap[f].platform=["ios","android","browser"]);f=projekktor(this.selector,c);j(this.selector).attr("id");f.addListener("state",function(b,a){if(a&&a.config){var c=
document.getElementById(a._id);switch(b){case "PLAYING":a.config.currentItemPlaying==-1&&a._bubbleEvent("item",a.getItemIdx());a.config.currentItemPlaying=a.getItemIdx();a.config.onPlay&&(typeof a.config.onPlay=="string"?(new Function(g(a.config.onPlay,a))).call(c):a.config.onPlay.call(a));break;case "PAUSED":a.config.onPause&&(typeof a.config.onPause=="string"?(new Function(g(a.config.onPause,a))).call(c):a.config.onPause.call(a));break;case "IDLE":a.config.onStop&&(typeof a.config.onStop=="string"?
(new Function(g(a.config.onStop,a))).call(c):a.config.onStop.call(a))}}});c.onUpdate&&f.addListener("time",function(b,a){if(a&&a.config){var c=document.getElementById(a._id);a.config.onUpdate&&(typeof a.config.onUpdate=="string"?(new Function(g(a.config.onUpdate,a))).call(c):a.config.onUpdate.call(a))}});(c.onChange||c.onNext||c.onPrevious)&&f.addListener("item",function(b,a){if(a&&a.config){var c=document.getElementById(a._id);a.config.onChange&&(typeof a.config.onChange=="string"?(new Function(g(a.config.onChange,
a))).call(c):a.config.onChange.call(a));a.config.onNext&&a.config.currentItemPlaying!=null&&b>a.config.currentItemPlaying&&(typeof a.config.onNext=="string"?(new Function(g(a.config.onNext,a))).call(c):a.config.onNext.call(a));a.config.onPrevious&&a.config.currentItemPlaying!=null&&b<a.config.currentItemPlaying&&(typeof a.config.onPrevious=="string"?(new Function(g(a.config.onPrevious,a))).call(c):a.config.onPrevious.call(a))}});return this}})(jQuery);
